### ISSUE TITLE
Add Pubspec.lock and other similar files to .gitignore

### ISSUE THREAD

**Issue by markhallak** [markhallak/AnxietyGo#24]

**Comment by vikas-shrma** [comment]
We need to follow some steps before going forward. because if git tracked any file after that he can't ignore that file
1. Delete pubspec.lock fle from the **master** and **dev** branch
2. And then again take fresh pull from git and start working normally as we are currently doing
3. or if that file found tracked or modified we have to run this command git update-index --assume-unchanged `pubspec.lock`

**Comment by markhallak** [comment]
If we delete the "pubspec.lock" file from both branches, it will still be generated locally. Right?

**Comment by vikas-shrma** [comment]
yes. its auto process by flutter framework based on pubspec.yaml file

**Comment by markhallak** [comment]
Understood.

So I am going to delete the file from both branches and whoever is going to work on the project has to do a new pull from git and then start working normally. That should fix it, right?

**Comment by vikas-shrma** [comment]
Right that is one way
Another one is everyone update their gitignore file with pubspec.lock  and run that command i commented in above comment
And then nobody push that file to github
And on the other side you deleted that file from both branches

**Comment by markhallak** [comment]
Understood. Thanks!
